test_that("use function1", {
  df <- data.frame(col1 = c("1", NA, 3), col2 = c("1", NA, "45"))
  out <- function1(df)
  expect_true("col1" %in% names(out))
  expect_true("col2" %in% names(out))
  expect_false(all(is.na(out$col1)))
  expect_false(all(is.na(out$col2)))
  expect_true(is.numeric(out$col1))
  expect_true(is.numeric(out$col2))
})
